# Generated by Django 5.2.17 on 2026-09-04 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('HOLIDAY', 'Holiday'), ('WEEKEND', 'Weekend'), ('LEAVE', 'Leave'), ('INCOMPLETE', 'Incomplete')], max_length=10)),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_in_source', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=10)),
                ('check_out_source', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=10)),
                ('manually_marked', models.BooleanField(default=False)),
                ('manual_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CHECK_IN', 'Check in'), ('CHECK_OUT', 'Check out'), ('MANUAL_CREATE', 'Manual create')], max_length=20)),
                ('old_data', models.JSONField(default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='attendance.attendance')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'attendance_date'], name='attendance__employe_37ed17_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date'], name='attendance__attenda_9d89bd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance__status_132c06_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['manually_marked'], name='attendance__manuall_88fccd_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_attendance_date'),
        ),
    ]
